# Generated by Django 5.2.3 on 2025-07-02 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_date_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 23, 1, 39, 354156)),
        ),
    ]
