# Generated by Django 5.2.3 on 2025-07-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_profile_date_modified_feature_productfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfeatures', to='store.feature')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='store.product')),
                ('subfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subfeature')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
